baseURL: "https://nunomtg.github.io/" 
title: Nuno Gonçalves
theme: PaperMod


enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: papers/
          weight: 1
        - name: News
          url: news/
          weight: 2 

params:
    description: "I am a final-year Master's student at Instituto Superior Técnico. I am currently working on dynamic sparse transformations and sparse loss functions."
    author: Nuno Gonçalves
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["papers","news"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    hideFooter: true
    profileMode:
          enabled: true
          title: Nuno Gonçalves
          subtitle: "I am a final-year Master's student at Instituto Superior Técnico. I am currently working on my thesis under the supervision of [Professor André Martins](https://andre-martins.github.io/), with my main focus being on dynamic sparse transformations, such as [Entmax](https://arxiv.org/abs/1905.05702), and [sparse loss functions](https://arxiv.org/abs/1901.02324)."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Papers
              url: papers/
            - name: News
              url: news/


    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:nuno.m.goncalves@tecnico.ulisboa.pt
        - name: GitHub
          url: https://github.com/nunomtg

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Nuno Gonçalves"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2